### ISSUE TITLE
bug: get_selected_cluster_id fails when multiple nodes are selected

### ISSUE THREAD

**Issue by russHyde** [jumpingrivers/tfpbrowser#38]
On the "Tree mutations" treeview. If multiple nodes are selected the app crashes with

```
Warning in ids$data_id == treeviewSelected :
  longer object length is not a multiple of shorter object length
Warning: Error in if: the condition has length > 1
```

We'd need to rethink how to handle having a 'treeviewSelected' vector longer than 1.

**Comment by jr-nicola** [comment]
In the ggiraph options, there were two calls to opts_selection:

```
ggiraph::opts_selection(type = "single"),
      ggiraph::opts_selection_inv(css = "fill:grey;"),
      ggiraph::opts_selection(css = "fill:red;"),
```

I suspect the second one is (quietly) over-writing the first one, and using the default `type = "multiple"`. I've now corrected this when making the other requested changes in #37 - should be fixed now.

**Comment by jr-nicola** [comment]
Actually, that hasn't fixed it - there are two things to select a node: the mutations drop down, and clicking one a node. My gut feeling is that the download files should only change when a user clicks on the graph (and not when they select a mutation), but I'll ask Erik

Example mutation: C11962T

**Comment by jr-nicola** [comment]
I've defaulted to use the first selected element since I don't think there's an easy way to distinguish between selected from custom message and selected by user clicking
